# used to fill missing taxonomy entries or convert domain to kingdom;
# more for use in conjunction with utax ITS reference database
kingdom: ""
taxonomy_database:
    fasta: ref/rdp_16s_trainset15/fasta/refdb.fa
    # joined read length dependent; utax taxconfs file
    trained_parameters: ref/rdp_16s_trainset15/taxconfs/250.tc
    # used in building report
    metadata: 'RDP Trainset database version 15 trained with UTAX 250 bp configuration'
    # citation for this tax database
    citation: "Cole, J. R., Q. Wang, J. A. Fish, B. Chai, D. M. McGarrell, Y. Sun, C. T. Brown, A. Porras-Alfaro, C. R. Kuske, and J. M. Tiedje. 2014. Ribosomal Database Project: data and tools for high throughput rRNA analysis Nucl. Acids Res. 42(Database issue):D633-D642; doi: 10.1093/nar/gkt1244 [PMID: 24288368]"
chimera_database:
    fasta: ref/chimera/rdp_gold.fa
    # used to build report
    metadata: 'RDP Gold reference database version 9'
    citation: "Cole, J. R., Q. Wang, J. A. Fish, B. Chai, D. M. McGarrell, Y. Sun, C. T. Brown, A. Porras-Alfaro, C. R. Kuske, and J. M. Tiedje. 2014. Ribosomal Database Project: data and tools for high throughput rRNA analysis Nucl. Acids Res. 42(Database issue):D633-D642; doi: 10.1093/nar/gkt1244 [PMID: 24288368]"
merging:
    # minimum passing read length after merging
    minimum_merge_length: 175
filtering:
    # fastas to parse into kmers which are then trimmed from the sequences
    adapters: ref/phix174_ill.ref.fa.gz,ref/adapters.fa
    # lower than 20 to allow overlap the chance to increase the quality
    minimum_base_quality: 10
    # kmer mismatches allowed during adapter trim process
    allowable_kmer_mismatches: 1
    # length of kmer to search against sequences
    reference_kmer_match_length: 31
    # passing single-end read length, prior to merging
    minimum_passing_read_length: 51
    # after merging; the allowable limit of erroneous bases; accepts fractions as well
    maximum_expected_error: 1
clustering:
    minimum_sequence_abundance: 2
    # maximum difference between an OTU member sequence and the representative sequence of that OTU
    percent_of_allowable_difference: 3
taxonomy:
    # OTU sequences are predicted at each phylogenetic level up to the point
    # where confidence dips below this threshold
    prediction_confidence_cutoff: 0.8
mapping_to_otus:
    # reflects the difference between OTU clusters to reduce ambiguous assignment
    read_identity_requirement: 0.97
