# prefilter out any sample with less than this many starting sequences
minimum_reads: 1000
# either use 'blast' or 'utax'
# with blast and SILVA, more sequences will be annotated with reasonable
# confidence
# with utax, fewer sequences will be annotated more preciously to what
# prediction_confidence_cutoff is set to below
annotation_method: blast
# 'true' or 'false'
# this is a reference-based chimera filter and is applied to OTU seed sequences
chimera_filter_seed_sequences: true
# used to fill missing taxonomy entries or convert domain to kingdom;
# more for use in conjunction with utax ITS reference database
kingdom: Fungi
utax_database:
    fasta: ref/unite_v7/fasta/refdb.fa
    # joined read length dependent; utax taxconfs file
    trained_parameters: ref/unite_v7/taxconfs/its2.tc
    # used in building report
    metadata: "Unite version 7 database trained on the ITS2 region"
    # citation for this tax database
    citation: "Koljalg, Urmas, et al. Towards a unified paradigm for sequence-based identification of fungi. Molecular Ecology 22.21 (2013): 5271-5277."
chimera_database:
    fasta: ref/unite_v7/blast/unite_7.fasta
    metadata: "Unite version 7 database"
    citation: "Koljalg, Urmas, et al. Towards a unified paradigm for sequence-based identification of fungi. Molecular Ecology 22.21 (2013): 5271-5277."
blast_database:
    fasta: ref/unite_v7/blast/unite_7.fasta
    taxonomy: ref/unite_v7/blast/unite_7.tax
    metadata: "Unite version 7 database"
    citation: "Koljalg, Urmas, et al. Towards a unified paradigm for sequence-based identification of fungi. Molecular Ecology 22.21 (2013): 5271-5277."
merging:
    # minimum passing read length after merging
    minimum_merge_length: 175
filtering:
    # fastas to parse into kmers which are then trimmed from the sequences
    adapters: ref/adapters.fa
    contaminants: ref/phix174_ill.ref.fa.gz
    # Look for shorter kmers at read tips down to this length; 0 disables
    mink: 8
    # lower than 20 to allow overlap the chance to increase the quality
    minimum_base_quality: 10
    # kmer mismatches allowed during adapter trim process
    allowable_kmer_mismatches: 1
    # length of kmer to search against sequences
    reference_kmer_match_length: 31
    # passing single-end read length, prior to merging
    minimum_passing_read_length: 51
    # after merging; the allowable limit of erroneous bases; accepts fractions as well
    maximum_expected_error: 1
    # {denoised, high_confidence, specific, balanced, sensitive}
    # denoised - reports all perfect chimeric models
    # high_confidence - high confidence, high false negative rate
    # specific - high confidence, high false-negative rate (just less so than high_confidence)
    # balanced - balance false negatives and false positives to minimize the overall error rate on typical data
    # sensitive - emphasizes high sensitivity at the expense of a high false positive rate
    chimera_mode: high_confidence
clustering:
    minimum_sequence_abundance: 2
    # maximum difference between an OTU member sequence and the representative sequence of that OTU
    percent_of_allowable_difference: 3
taxonomy:
    # OTU sequences are predicted at each phylogenetic level up to the point
    # where confidence dips below this threshold
    prediction_confidence_cutoff: 0.8
    # comma separated list of min % identity to accept a database hit at a
    # taxonomic level; Species to Kingdom
    lca_cutoffs: 99,97,95,90,85,80,0
mapping_to_otus:
    # reflects the difference between OTU clusters to reduce ambiguous assignment
    read_identity_requirement: 0.97
